name: pytest

on:
  push:
    branches:
    - master
    - development
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        env: [
          '-r requirements.txt .[test]',
          '-r requirements-min.txt .[test]',
          '--upgrade --upgrade-strategy=eager .[test]'
        ]
        exclude:
          - python-version: 3.8
            env: '-r requirements-min.txt .[test]'
          - python-version: 3.9
            env: '-r requirements-min.txt .[test]'
          - python-version: "3.10"
            env: '-r requirements-min.txt .[test]'
          # required numpy is not available on python 3.7, so exclude:
          - python-version: 3.7
            env: '-r requirements.txt .[test]'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ${{ matrix.env }}
      run: |
        python -m pip install --upgrade pip wheel
        pip install --timeout=300 ${{ matrix.env }}
    - name: Test with pytest ${{ matrix.env }}
      run: |
        pytest
